repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format
        files: ^.+\.py$
      - id: ruff
        args: [ --fix ]
        files: ^.+\.py$
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ --py310-plus ]
  - repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.5.0
          - pydocstyle==5.0.2
        files: ^.+\.py$
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=tests/bandit.yaml
        files: ^.+\.py$
        exclude: ^[^/]+\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        files: ^.+\.json$
      - id: trailing-whitespace
      # Uncomment lines below if you want to follow classical GitHub flow style development
#      - id: no-commit-to-branch
#        args:
#          - --branch=dev
  - repo: local
    hooks:
      # Run mypy through our wrapper script in order to get the possible
      # pyenv and/or virtualenv activated; it may not have been e.g. if
      # committing from a GUI tool that was not launched from an activated
      # shell.
      - id: mypy
        name: mypy
        entry: scripts/run-in-env mypy
        language: script
        types: [python]
        require_serial: true
        files: ^.+\.py$
      # Uncomment lines below to test code on every commit
#      - id: pytest
#        name: pytest
#        entry: scripts/run-in-env pytest
#        language: system
#        pass_filenames: false
#        always_run: true
