#!/bin/sh
# Setups the repository.

# Stop on errors
set -e

ROOT="$( cd "$( dirname "$(readlink -f "$0")" )/.." >/dev/null 2>&1 && pwd )"

cd "${ROOT}"
script/bootstrap

pre-commit install
pip3 install -e .
